# Generated by Django 5.0.6 on 2024-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_property_product_delete_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
