# Generated by Django 5.0.6 on 2024-07-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sell_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='product.color'),
        ),
    ]
