# Generated by Django 5.0.6 on 2024-07-09 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category/posters')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='category.category')),
            ],
        ),
    ]
