# Generated by Django 5.0.6 on 2024-07-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_alter_feature_product_alter_info_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='value',
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='SubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=150)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_info', to='feature.info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
